my_blog/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.PostView.as_view()),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('review/<int:pk>/', views.AddComments.as_view(), name='add_comments'),
    path('<int:pk>/add_likes/', views.AddLike.as_view(), name='add_likes'),
    path('fotoalbum/', views.Foto.as_view(), name='fotoalbum'),
    path('about_my/', views.AboutMy.as_view(), name='about_my')
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/blog/models.py
from django.db import models


class Post(models.Model):
    '''данные о посте'''
    title = models.CharField('Заголовок записи', max_length=100)
    description = models.TextField('Текст записи')
    author = models.CharField('Имя автора', max_length=100)
    date = models.DateField('Дата публикации')
    img = models.ImageField('Изображение', upload_to='image/%Y')

    def __str__(self):
        return f'{self.title}, {self.author}'

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'


class Comments(models.Model):
    '''Коментарии'''
    email = models.EmailField()
    name = models.CharField('Имя', max_length=50)
    text_comments = models.TextField('Текст комментария', max_length=2000)
    post = models.ForeignKey(Post, verbose_name='Публткация', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}, {self.post}'

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Likes(models.Model):
    '''Лайки'''
    ip = models.CharField('IP-адрес', max_length=100)
    pos = models.ForeignKey(Post, verbose_name='Публикация', on_delete=models.CASCADE)

my_blog/blog/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from .models import Post, Likes
from .form import CommentsForm

class PostView(View):
    '''вывод записей'''
    def get(self, request):
        posts = Post.objects.all
        return render(request, 'blog/title.html', {'post_list': posts})


class PostDetail(View):
    '''Отдельная страница поста'''
    def get(self, request, pk):
        post = Post.objects.get(id=pk)
        return render(request, 'blog/detail1.html', {'post': post})


class AddComments(View):
    '''добавление комментариев'''
    def post(self, request, pk):
        form = CommentsForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.post_id = pk
            form.save()
        return redirect(f'/{pk}')


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

class AddLike(View):
    def get(self, request, pk):
        ip_client = get_client_ip(request)
        try:
            Likes.objects.get(ip=ip_client, pos_id=pk)
            return redirect(f'/{pk}')
        except:
            new_like = Likes()
            new_like.ip = ip_client
            new_like.pos_id = int(pk)
            new_like.save()
            return redirect(f'/{pk}')

class Foto(View):
    def get(self, request):
        post = Post.objects.all
        return render(request, 'blog/fotoalbum.html', {'post': post})

class AboutMy(View):
    def get(self, request):
        return render(request, 'blog/about_my.html')

my_blog/templates/blog/about_my.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title_list</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>

<body>
    <div class="container-fluid">
        <ul class="nav justify-content-center">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">ГЛАВНАЯ</a>
          </li>
        </ul>
    </div>

    <div class="container-fluid">
        <ul class="nav justify-content-center">
            <div class="card" style="width: 18rem;">
              <img src="../../media/image/2023/jac%20if%20custo.jpg" class="card-img-top" alt="img">
              <div class="card-body">
                <p class="card-text">Жак-Ив Кусто́ (фр. Jacques-Yves Cousteau; 11 июня 1910, Сент-Андре-де-Кюбзак, Бордо,
                    Франция — 25 июня 1997, Париж, Франция) — французский исследователь Мирового океана, фотограф,
                    режиссёр, изобретатель, автор множества книг и фильмов. Являлся членом Французской академии.
                    Командор ордена Почётного легиона. Известен как Капитан Кусто (фр. Commandant Cousteau).
                    Совместно с Эмилем Ганьяном в 1943 году разработал и испытал акваланг.
                    В его честь назван уступ Кусто на Плутоне.
                </p>
              </div>
            </div>
        </ul>
    </div>

</body>
</html>

my_blog/templates/blog/detail1.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title_list</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>

<body>
    <div class="container-fluid">
        <ul class="nav justify-content-center">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">ГЛАВНАЯ</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/fotoalbum/">ФОТОАЛЬБОМ</a>
          </li>
        </ul>
    </div>

    <div class="alert alert-secondary" role="alert" align="center">
        <h4>{{ post.title }}</h4>
    </div>
    <p align="center">
        <img src="{{ post.img.url }}" alt="img" width="40%">
    </p>
    <div class="alert alert-secondary" role="alert" align="center">
        <a href="{% url 'add_likes' post.id %}"><h3>Нравится</h3></a>Понравилось:{{ post.likes_set.all.count }}
    </div>

    <div style="margin: 0px 70px">
        <p>{{ post.description }}</p>
        <p>{{ post.author }}</p>
    </div>

    <div class="alert alert-secondary" role="alert" align="center" style="color:dodgerblue">
        <div class="form-comment">
		<h3>Оставить коментарий</h3>
		<div>
			<form action="{% url 'add_comments' post.id %}" method="post">
				{% csrf_token %}
				<div>
					<label>Ваш комментарий</label>
					<textarea name="text_comments"></textarea>
				</div>
				<div>
					<label>Ваше имя *</label>
					<input type="text" name="name">
				</div>
				<div>
					<label>Ваше Email *</label>
					<input type="email" name="email">
				</div>

				<div>
					<input type="submit">
				</div>
			</form>
		</div>
    </div>
        <div class="alert alert-secondary" role="alert" align="center">
                {% for comment in post.comments_set.all %}
                <div class="view-comment">
                    <h4>{{ comment.name }} прокоментировал:</h4>
                    <p>
                        {{ comment.text_comments }}
                    </p>
                </div>
                {% endfor %}
        </div>
</body>
</html>

my_blog/templates/blog/fotoalbum.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Photo_album</title>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
  </head>

<body>
    <div class="container-fluid">
        <ul class="nav justify-content-center">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">ГЛАВНАЯ</a>
        </ul>
    </div>
    <div class="container-fluid my-carousel">
        <div id="carouselExample" class="carousel slide">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="../../media/image/2023/istanbulhostels.jpeg" class="d-block w-100" alt="img">
            </div>
            <div class="carousel-item">
              <img src="../../media/image/2023/romethings.jpeg" class="d-block w-100" alt="img">
            </div>
            <div class="carousel-item">
              <img src="../../media/image/2023/japanfirsttime1.jpeg" class="d-block w-100" alt="img">
            </div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
    </div>
</body>

my_blog/templates/blog/title.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title_list</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
    <div id="fon">
      <img src="../../media/image/2023/ua.jpg" width="100%" height="300px">
        <p class="text-center">My travel blog</p>
    </div>

<ul class="nav justify-content-center">
  <li class="nav-item">
    <a class="nav-link active" aria-current="page" href="/">ГЛАВНАЯ</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/fotoalbum/">ФОТОАЛЬБОМ</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="about_my/">О БО МНЕ</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" target="_blank" href="/admin">АДМИН ПАНЕЛЬ</a>
  </li>
</ul>
    <div>
        <div class="container text-center">

              <div class="row row-cols-2 row-cols-lg-3 g-2 g-lg-3">
                  {% for post in post_list %}
                <div class="col">
                  <div class="p-3"><a href="#"><img src="{{ post.img.url }}" alt="img" width="230px" height="150px"/></a></div>
                  <a href="{{ post.id }}"> {{ post.title }}</a>
                </div>
                  {% endfor %}
              </div>

        </div>
    </div>


</body>
</html>